export const NEW_DASHBOARD_REQUEST = 'NEW_DASHBOARD_REQUEST';
export const NEW_DASHBOARD_SUCCESS = 'NEW_DASHBOARD_SUCCESS';
export const NEW_DASHBOARD_FAILURE = 'NEW_DASHBOARD_FAILURE';

export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';

export const UPDATE_DASHBOARD_REQUEST = 'UPDATE_DASHBOARD_REQUEST';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const UPDATE_DASHBOARD_FAILURE = 'UPDATE_DASHBOARD_FAILURE';

export const REMOVE_DASHBOARD_REQUEST = 'REMOVE_DASHBOARD_REQUEST';
export const REMOVE_DASHBOARD_SUCCESS = 'REMOVE_DASHBOARD_SUCCESS';
export const REMOVE_DASHBOARD_FAILURE = 'REMOVE_DASHBOARD_FAILURE';

export const NEW_CARD_REQUEST = 'NEW_CARD_REQUEST';
export const NEW_CARD_SUCCESS = 'NEW_CARD_SUCCESS';
export const NEW_CARD_FAILURE = 'NEW_CARD_FAILURE';

export const GET_CARD_REQUEST = 'GET_CARD_REQUEST';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILURE = 'GET_CARD_FAILURE';

export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILURE = 'UPDATE_CARD_FAILURE';

export const REMOVE_CARD_REQUEST = 'REMOVE_CARD_REQUEST';
export const REMOVE_CARD_SUCCESS = 'REMOVE_CARD_SUCCESS';
export const REMOVE_CARD_FAILURE = 'REMOVE_CARD_FAILURE';

export const NEW_COLUMN_REQUEST = 'NEW_COLUMN_REQUEST';
export const NEW_COLUMN_SUCCESS = 'NEW_COLUMN_SUCCESS';
export const NEW_COLUMN_FAILURE = 'NEW_COLUMN_FAILURE';

export const GET_COLUMN_REQUEST = 'GET_COLUMN_REQUEST';
export const GET_COLUMN_SUCCESS = 'GET_COLUMN_SUCCESS';
export const GET_COLUMN_FAILURE = 'GET_COLUMN_FAILURE';

export const UPDATE_COLUMN_REQUEST = 'UPDATE_COLUMN_REQUEST';
export const UPDATE_COLUMN_SUCCESS = 'UPDATE_COLUMN_SUCCESS';
export const UPDATE_COLUMN_FAILURE = 'UPDATE_COLUMN_FAILURE';

export const REMOVE_COLUMN_REQUEST = 'REMOVE_COLUMN_REQUEST';
export const REMOVE_COLUMN_SUCCESS = 'REMOVE_COLUMN_SUCCESS';
export const REMOVE_COLUMN_FAILURE = 'REMOVE_COLUMN_FAILURE';

export const SET_CARD_OPEN = 'SET_CARD_OPEN';
export const CLOSE_CARD_OPEN = 'CLOSE_CARD_OPEN';

export const CHANGE_CARD_NAME = 'CHANGE_CARD_NAME';

export const SET_CARD_DRAG_SOURCE = 'SET_CARD_DRAG_SOURCE';
export const SET_COLUMN_DRAG_SOURCE = 'SET_COLUMN_DRAG_SOURCE';

export const REPLACE_CARD_REQUEST = 'REPLACE_CARD_REQUEST';
export const REPLACE_CARD_SUCCESS = 'REPLACE_CARD_SUCCESS';
export const REPLACE_CARD_FAILURE = 'REPLACE_CARD_FAILURE';

export const REPLACE_COLUMN_REQUEST ='REPLACE_COLUMN_REQUEST';
export const REPLACE_COLUMN_SUCCESS = 'REPLACE_COLUMN_SUCCESS';
export const REPLACE_COLUMN_FAILURE = 'REPLACE_COLUMN_FAILURE';

