export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_IS_AUTH = 'SET_IS_AUTH';


export const REQUEST_DASHBOARD_LIST = 'REQUEST_DASHBOARD_LIST';
export const INVALIDATE_DASHBOARD_LIST='INVALIDATE_DASHBOARD_LIST';
export const RECEIVE_DASHBOARD_LIST='RECIEVE_DASHBOARD_LIST';

export const REQUEST_NOTIFICATION_LIST = 'REQUEST_NOTIFICATION_LIST';
export const INVALIDATE_NOTIFICATION_LIST='INVALIDATE_NOTIFICATION_LIST';
export const RECEIVE_NOTIFICATION_LIST='RECIEVE_NOTIFICATION_LIST';

export const REQUEST_PROFILE_DATA = 'REQUEST_PROFILE_DATA';
export const INVALIDATE_PROFILE_DATA='INVALIDATE_PROFILE_DATA';
export const RECEIVE_PROFILE_DATA='RECEIVE_PROFILE_DATA';

