export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';

export const GET_MESSAGES = 'SET_MESSAGES';

export const SEND_MESSAGE_REQUEST= 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SECCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE= 'SEND_MESSAGE_FAILURE';